apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "yurt-edgex-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "yurt-edgex-manager.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "yurt-edgex-manager.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      - args:
        - --secure-listen-address=0.0.0.0:8443
        - --upstream=http://127.0.0.1:8080/
        - --logtostderr=true
        - --v=10
        image: "{{ .Values.rbacproxy.image }}:{{ .Values.rbacproxy.tag }}"
        name: kube-rbac-proxy
        ports:
        - containerPort: 8443
          name: https
      - args:
        - --health-probe-bind-address=:8081
        - --metrics-bind-address=127.0.0.1:8080
        - --leader-elect
        {{- range $arg := .Values.edgexmanagerargs }}
        - {{ $arg }}
        {{- end }}
        command:
        - /manager
        image: "{{ .Values.edgexmanager.image }}:{{ .Values.edgexmanager.tag }}"
        name: {{ include "yurt-edgex-manager.fullname" . }}
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
        readinessProbe:
          httpGet:
            path: /readyz
            port: 8081
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
        {{- with .Values.resources }}
        resources:
          {{- toYaml . | nindent 10 }}
        {{- end }}
        securityContext:
          allowPrivilegeEscalation: {{ .Values.securityContext.allowPrivilegeEscalation }}
      securityContext:
        runAsNonRoot: {{ .Values.securityContext.runAsNonRoot }}
      serviceAccountName: {{ include "yurt-edgex-manager.serviceAccountName" . }}
