apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "yurt-edgex-manager.fullname" . }}-rolebinding
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "yurt-edgex-manager.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "yurt-edgex-manager.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
