apiVersion: v1
kind: Service
metadata:
  labels:
    control-plane: controller-manager
  name: {{ include "yurt-edgex-manager.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  ports:
  - name: https
    port: {{ .Values.service.port }}
    targetPort: https
  selector:
    {{- include "yurt-edgex-manager.selectorLabels" . | nindent 4 }}
